### ISSUE TITLE
小米手机，当前小米系统miui11.0.7安卓9。会出现视频画面显示不全就占总屏幕的2%不到

### ISSUE THREAD

**Issue by hajime-early** [shanmaomaoymmm/hiwara#12]
![QQ截图20240114023039](https://github.com/shanmaomaoymmm/hiwara/assets/139116660/3c90a419-c450-4a4a-96bb-1bb14f09ff87)
红色圈出来的部分是播放视频的位置。就这么点大小。也没法调整。
以防图炸了[问题图](https://i.postimg.cc/sD8sVXfX/Screenshot-2024-01-14-02-27-21-318-com-qisato-hiw.jpg)

**Comment by zylancet233** [comment]
我也是这个问题  米11u MIUI12.5.11
